server:
  port: 8088
spring:
  application:
    name: KaiBaiShopping
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/shopping?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: qweasd123
    driver-class-name: com.mysql.cj.jdbc.Driver